services:
  app:
    image: node:18-alpine
    container_name: web
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres

  postgres:
    image: postgres:14.0
    container_name: postgresdb
    ports:
      - 5432:5432
    volumes:
      - todo-postgres-data:/var/lib/postgresql/data
    environment:
      PGUSER: postgres
      PGHOST_AUTH_METHOD: trust
      PGDATABASE: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  todo-postgres-data:
    name: postgresVol
